# Generated by Django 5.1.1 on 2024-10-11 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_rename_amount_transaction_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Nome completo'),
            preserve_default=False,
        ),
    ]
